config/routes.rb
Rails.application.routes.draw do

  root to: "lists#index"

  resources :lists do
    resources :tareas
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
validates :URL, uniqueness:true
validates :URL, presence:true


  has_many :tareas, dependent: :destroy

  extend FriendlyId
  friendly_id :URL, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end
end

app/models/long.rb
class Long < Tarea
# validates :percentage, :numericality => { :less_than_or_equal_to => 100, :greater_than_or_equal_to => 0,
# :only_integer => true}, :presence => true
validates :percentage, presence:true
validates :porcentaje? ,  presence: true

 def porcentaje?
   if percentage
       if  percentage < 101 && percentage > -1
          return true
       else
          return false
       end
   end
 end

  # validates_numericality_of :percentage,
  #   :less_than_or_equal_to => 100,
  #   :greater_than_or_equal_to => 0,
  #   :only_integer => true
end

app/models/simple.rb
class Simple < Tarea
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  belongs_to :list
validates :type, presence:true
end

app/models/temporary.rb
class Temporary < Tarea

  validates :end_time, presence:true
  validates :begin_time, presence:true
 validates :fecha_es_posible? ,  presence: true

  def fecha_es_posible?
    if end_time && begin_time
        if end_time < begin_time
           return false
        else
           return true
        end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if cookies[:user_lists].nil?
      @lists = List.none
    #  if @lists.size > 5
    #    @lists= @lists.last(5)
    #  end
    else
      ids = cookies[:user_lists].split("&")
      @lists = List.all.find(ids).last(5).reverse
    #  Rails.logger.debug @Lists
    end
    @list = List.new
  end

  def show
    @list=List.friendly.find(params[:id])
    @tareas=@list.tareas.all

  end


  def destroy
    @list=List.friendly.find(params[:id])
    eliminar @list.id
    List.friendly.find(params[:id]).destroy
    redirect_to lists_url
  end

  def edit
    @list=List.friendly.find(params[:id])
    @tareas=@list.tareas.all

  end

  def update
    @list=List.friendly.find(params[:id])
    @list.update(list_params_to_update)
		redirect_to edit_list_path
  end

  def create
    @list = List.new(list_params)
    #en caso de crear con tarea @list.tareas.new(tarea_params)
   respond_to do |format|
      if @list.save
        agregar @list.id
        format.html { redirect_to @list, notice: 'Lista satisfactoriamente creada.' }
      else
        format.html { redirect_to @list, notice: 'La lista no se pudo crear' }
      end
    end
  end

  private

    def list_params_to_update
		    list_params.permit(:URL)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:created_at, :updated_at, :name, :URL)
    end

    def tarea_params
		    params.require(:tarea).permit(:description)
	  end

    def agregar id_lista
      if cookies[:user_lists].nil?
        cookies[:user_lists]=Array.new
        cookies[:user_lists].push(id_lista)
      else
      # en caso de ser necesario .gsub('+', ' ')
        arreglo = cookies[:user_lists].split("&")
        arreglo.push(id_lista)
        cookies[:user_lists] = arreglo
      end
    end

    def eliminar id_lista
      arreglo = cookies[:user_lists].split("&")
      Rails.logger.debug arreglo
      Rails.logger.debug 'DESPUES DE ARREGLO'
      arreglo.delete(id_lista.to_s)
      Rails.logger.debug arreglo
      cookies[:user_lists] = arreglo
    end

end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
before_action :set_todo_list

def create
  @tarea = @list.tareas.create(tarea_params)
  respond_to do |format|
     if @tarea.save
       format.html { redirect_to @list, notice: 'Tarea satisfactoriamente creada.'}
     else
       format.html { redirect_to @list, notice: 'La Tarea no se pudo crear.'}
     end
   end
end


def edit
  @tarea=@list.tareas.find(params[:id])
end

def update
    @tarea=@list.tareas.find(params[:id])
    cambia_estado @tarea
    respond_to do |format|
    if @tarea.update(tarea_params_to_update)
      format.html { redirect_to @list, notice: 'Tarea  modificada.'}
    else
      format.html { redirect_to @list, notice: 'La Tarea no se pudo modificar.'}
    end
  end
end


def destroy
  @tarea = @list.tareas.find(params[:id])
  respond_to do |format|
  if @tarea.destroy
    format.html { redirect_to @list, notice: 'Tarea Eliminada.'}
  else
    format.html { redirect_to @list, notice: 'La Tarea no se pudo eliminar.'}
  end
end
end


private
  def cambia_estado tarea
    if tarea.type == 'Temporary'
      if tarea.end_time< Date.today
        tarea.state = 'Expirada'
      end
  end
  end

  def tarea_params_to_update
      tarea_params.permit(:description,:priority,:state,:percentage,:begin_time,:end_time)
  end

  def set_todo_list
    @list = List.friendly.find(params[:list_id])
  end

  def tarea_params
		params.require(:tarea).permit(:description, :type, :priority, :state,:begin_time, :end_time, :percentage)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :URL %>
    <%= f.text_field :URL %>
    
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.datetime_select :created_at %>
  </div>

  <div class="field">
    <%= f.label :updated_at %>
    <%= f.datetime_select :updated_at %>
  </div>


  <legend>Datos de tarea</legend>
  		<%= fields_for :tareas do |t| %>
      		<div class='field'>
      		<%= t.label :tipo_de_tarea %><br>
      		<%= t.select :type, [['Simple','Simple'],[ 'Temporal','Temporary'],['Larga','Long']],:required => true  %> <br>
      		</div>
      		<div class='field'>
      		<%= t.label :forma_de_descripcion %><br>
      		<%= t.text_field :description ,placeholder:"Ingrese una descripcion",:required => true %>
      		</div>
      	<% end %>
      	</fieldset>

  		<div class='actions'>
  		<%= f.submit %>
  		</div>

<% end %>

app/views/lists/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h1>Modificar Nombre Lista</h1>
  <%= link_to 'Atras', list_path(@list) %>

  <%= simple_form_for @list do |f| %>
    <%= f.input :URL, label: 'Cambiar Nombre', placeholder: :URL %>
    <%= f.button :submit, class: "btn-success" %>
  <% end %>

</body>
</html>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mostrara las listas del usuario, como máximo las últimas 5 listas creadas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Creada el</th>
      <th>Modificada el</th>
      <th>Url</th>
      <th>Vista|Modificar|Borrar</th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= l list.created_at %></td>
        <td><%= l list.updated_at %></td>
        <td><%= list.URL %></td>
        <td><%= link_to list_path(list), class: "btn btn-default" do%>
          <i class="glyphicon glyphicon-search"></i>
            <% end %>
          <%= link_to edit_list_path(list), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        <%= link_to list_path(list),method: :delete, data: { confirm: 'Esta seguro que quiere eliminar la Lista?' }, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash"></i>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= simple_form_for @list do |f| %>
  <%= f.input :URL, label: 'Nueva URL', placeholder: 'Introduce el nombre de la nueva lista' %>
  <%= f.button :submit, class: "btn-success" %>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Vista de lista</h1>

<div class="panel panel-default">

  <div class="panel-heading"><strong>Nombre:</strong> <%= @list.URL %></div>
  <div class="panel-heading"><strong>Creada el:</strong> <%= l @list.created_at %></div>
  <div class="panel-heading"><strong>Modificada el:</strong> <%= l @list.updated_at %></div>
  <div class="panel-heading"><strong>Link a la lista:</strong> <%= link_to "localhost:3000/lists/#{@list.friendly_id}", "localhost:3000/lists/#{@list.friendly_id}"  %></div>
<table class="table">
  <thead>
    <tr>
      <th>Prioridad</th>
      <th>Estado</th>
      <th>Descripcion</th>
      <th>Tipo</th>
      <th>Fecha Inicio</th>
      <th>Fecha Fin</th>
      <th>Porcentaje</th>
      <th>Acciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @list.tareas.order(priority: :asc).each do |tarea| %>
    <!-- <% if tarea.end_time
            if tarea.end_time< Date.today
      tarea.state = 'Expirada' %>
      <% end %>
      <% end %> -->
    <% if tarea.state == 'Hecha' %>
         <tr class="success">
      <% elsif tarea.state == 'Expirada' %>
        <tr class="danger">
      <% else %>
        <tr>
        <% end %>
        <%#  Date.today.between?(Date.yesterday, Date.tomorrow)%>
        <td><%= case tarea.priority
                  when 1
                     'Alta'
                  when 2
                     'Media'
                  else
                     'Baja'
                  end%></td>
        <td><%= tarea.state %></td>
        <td><%= tarea.description %></td>
        <td><%= tarea.type %></td>

        <td><%= if tarea.begin_time
          l tarea.begin_time, :format => :short
        end%></td>
        <td><%= if tarea.end_time
        l tarea.end_time, :format => :short end%></td>
        <td><%= if !tarea.percentage.nil?
              progress_bar tarea.percentage.to_f/100 ,alternative: 'success', striped: true, active: true, label: true, style: 'min-width: 20px' end %></td>
        <td>
          <%= link_to edit_list_tarea_path(@list,tarea), class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-edit"></i>
          <% end %>
        <%= link_to list_tarea_path(@list,tarea),method: :delete, data: { confirm: 'Esta seguro que quiere eliminar la tarea?' }, class: "btn btn-default" do %>
            <i class="glyphicon glyphicon-trash"></i>
        <% end %></td>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= render "tareas/form"%>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/tareas/_form.html.erb
<table class="table">
  <tr>
    <th class="success">Descripcion</th>
    <th class="success">Tipo</th>
    <th class="success">Prioridad</th>
    <th class="success"> </th>
  </tr>


  <tr>
    <td>
<%= simple_form_for([@list, @list.tareas.build]) do |f| %>
<div class="form-group">
  <%= f.text_field :description, placeholder: "Escriba desripcion para nueva Tarea",class:"form-control" %>
  <%= f.hidden_field :state, value: "Pendiente" %>
</div>
</td>
<td>
<div class="form-group">
  <%= f.select :type, [['Simple','Simple'],[ 'Larga','Long'],[ 'Temporaria','Temporary']],:required => true%><br>
  <%= content_tag :div, class: 'js-dependent-fields', data: {'select-id': 'tarea_type', 'option-value': 'Temporary'} do %>
    <%= f.date_field :begin_time, min: Date.today%><br>
    <%= f.date_field :end_time, min: Date.today%>
  <% end %>
  <%= content_tag :div, class: 'js-dependent-fields', data: {'select-id': 'tarea_type', 'option-value': 'Long'} do %>
    <%= f.input :percentage, input_html: { min: 0, max: 100} %><br>
  <% end %>
</div>
</td>
<td>
<div class="form-group">
  <%= f.select( :priority, [['Alta','1'],[ 'Media','2'],[ 'Baja','3']]) %>
</div>
</td>
<td>
  <%= f.submit class: "btn btn-success"%>
  <% end %>
</td>

</table>

app/views/tareas/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h1>Modificar Tarea</h1>
  <%= link_to 'Atras', list_path(@list) %>

  <%= simple_form_for @tarea.becomes(Tarea), url: list_tarea_path , method: :put do |t| %>
  <%= hidden_field_tag t.object = @tarea.becomes(@tarea.class) %>
  <%= t.input :description, label: 'Cambiar Descripción', placeholder: :description %>
  <label>Prioridad</label>
  <%= t.select( :priority, [['Alta','1'],[ 'Media','2'],[ 'Baja','3']])%>
  <label>Estado</label>
    <% if t.object.class == Long %>
    <%= t.select(:state, [['Pendiente'],['En Curso'],['Hecha']])%>
    <%= t.input :percentage, input_html: { min: 0, max: 100} %>
    <% else %>
    <%= t.select(:state, [['Pendiente'],['Hecha']])%>
    <% end%>
    <% if t.object.class == Temporary %>
    <%= content_tag :div, class: 'js-dependent-fields', data: {'select-id': 'tarea_type', 'option-value': 'Temporary'} do %>
    <label>Fecha Inicio </label>  <%= t.date_field :begin_time, min: Date.today%>
    <label>Fecha Fin </label>     <%= t.date_field :end_time, min: Date.today%>
      <% end %>
      <% end %>
  <%= t.button :submit, class: "btn-success" %>
  <% end %>

</body>
</html>